# Generated by Django 5.0.6 on 2024-06-29 00:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Servicio Adicional',
                'verbose_name_plural': 'Servicios Adicionales',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='hoteles', verbose_name='Imagen')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='adminHoteles.comuna')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio por noche')),
                ('cantidadCamas', models.PositiveIntegerField(verbose_name='Cantidad de camas')),
                ('cantidadBanos', models.PositiveIntegerField(verbose_name='Cantidad de baños')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHoteles.hotel', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('servicios', models.ManyToManyField(blank=True, to='adminHoteles.servicioadicional', verbose_name='Servicios Adicionales')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminHoteles.tipohabitacion')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
    ]
