# Generated by Django 5.0.6 on 2024-06-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHoteles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupada', 'Ocupada'), ('Mantenimiento', 'Mantenimiento'), ('Reservada', 'Reservada'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=50, verbose_name='Estado'),
        ),
    ]
